Add main branch

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -2,7 +2,12 @@
 
 branch="$(git rev-parse --abbrev-ref HEAD)"
 
+if [ "$branch" = "main" ]; then
+  echo "You can't commit directly to the $branch branch"
+  exit 1
+fi
+
 if [ "$branch" = "master" ]; then
-  echo "You can't commit directly to master branch"
+  echo "You can't commit directly to the $branch branch"
   exit 1
 fi
